### ISSUE TITLE
Error creating key.key files in new branch

### ISSUE THREAD

**Issue by MaxCaryMusic** [MaxCaryMusic/Python-Practice#3]
I'm running into issues with the load_key function in split_and_simple branch. 

I deleted the passwords.txt, masterpassword.txt, and key.key files from my machine to see if the 'check' and 'write' functions worked as intended, and I'm getting "file not found" errors:

Traceback (most recent call last):
  File "c:\Users\Maxwell Cary\Desktop\Python Practice\pw_mgr\password_manager.py", line 2, in <module> 
    from lib.crypto_utils import init_key
  File "c:\Users\Maxwell Cary\Desktop\Python Practice\pw_mgr\lib\crypto_utils.py", line 42, in <module>
    key = load_key()
  File "c:\Users\Maxwell Cary\Desktop\Python Practice\pw_mgr\lib\crypto_utils.py", line 37, in load_key
    file = open("key.key", "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'key.key'

these reference this line from crypto_utils.py

def load_key():
        file = open("key.key", "rb")
        key = file.read()
        file.close()
        return key

key = load_key()
fer = Fernet(key)

What's throwing me is that the program doesn't even call these functions before it throws the error message, which tells me that the script is looking for key.key before it has a chance to know it has to write them? Does this have to do with how the functions are being imported?

**Comment by ccary64** [comment]
So keep in mind that the location of the file is based off of where you are running the file in the command line for example if you are in c:\Users\Maxwell Cary\Desktop\Python Practice\pw_mgr and you run the script then it will expect it to be c:\Users\Maxwell Cary\Desktop\Python Practice\pw_mgr\key.key. One way to mitigate this is to use the location of the file instead of the location of where the script is running using __file__
